### ISSUE TITLE
node throw err

### ISSUE THREAD

**Issue by eliezergu** [Dexus/pem#92] opened 2016-11-11 20:00 UTC
i tried to run the the code given in the example i tried basic https and i got an err can't read property serviceKey of undefined so i installed express and tried the example given for express and i got err requireAuth is not defined.
i just copy past the code so it wasn't a typo

**Comment by Dexus** [comment] 2016-11-29 09:08
the requireAuth was a fail because copy&past from a personal project as example code - never trust examples think self and do not copy & paste 😈  ( or try "rm -rf /" to solve all your problems... - mad joke i know... ) 

i cant reproduce the problem that you provide with serviceKey... maybe you should take a look in you err.

**Comment by Dexus** [comment] 2016-12-01 09:02
If you have any additional details for your problem or other questions to this issue, reopen it or answer to this issue. I close it now.

**Closed as completed by Dexus** 2016-12-01 09:02 UTC
